export const CREATE_PAGE = "CREATE_PAGE";
export const RETRIEVE_PAGES = "RETRIEVE_PAGES";
export const UPDATE_PAGE = "UPDATE_PAGE";
export const DELETE_PAGE = "DELETE_PAGE";
export const DELETE_ALL_PAGES = "DELETE_ALL_PAGES";

export const RETRIEVE_STATS = "RETRIEVE_STAT";

export const CREATE_CRITERIA = "CREATE_CRITERIA";
export const RETRIEVE_CRITERIAS = "RETRIEVE_CRITERIAS";
export const UPDATE_CRITERIA = "UPDATE_CRITERIA";
export const DELETE_CRITERIA = "DELETE_CRITERIA";
export const DELETE_ALL_CRITERIAS = "DELETE_ALL_CRITERIAS";

export const CREATE_PROJECT = "CREATE_PROJECT";
export const RETRIEVE_PROJECTS = "RETRIEVE_PROJECTS";
export const UPDATE_PROJECT = "UPDATE_PROJECT";
export const DELETE_PROJECT = "DELETE_PROJECT";
export const DELETE_ALL_PROJECTS = "DELETE_ALL_PROJECTS";